eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8763/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
server:
  port: 8761